version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: /Users/dlobron/personal/ChugBot/ChugBot
            dockerfile: php.Dockerfile
        depends_on:
            - db
        volumes:
            - /Users/dlobron/personal/ChugBot/ChugBot/chugbot:/var/wwww/html
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: chugbot_test
            MYSQL_USER: admin
            MYSQL_PASSWORD: debug_password
            MYSQL_HOST: db
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: chugbot_test
            MYSQL_USER: admin
            MYSQL_PASSWORD: debug_password
        volumes:
            - "/Users/dlobron/personal/ChugBot/ChugBot/Docker/ChugBotWithDataProdVers.sql:/docker-entrypoint-initdb.d/1.sql"
        ports:
            - "9906:3306"